---
- name: Install httpd
  hosts: localhost

  - name: Install the httpd rpm
    yum: 
      name: httpd
      state: latest
  - name: start the httpd service
    service: 
      name: httpd 
      state: started